apiVersion: v1
kind: Service
metadata:
  name: voting-app-onprem-fixed-service
  labels:
    app: voting-app-onprem-fixed
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31515
  selector:
    app: voting-app-onprem-fixed