apiVersion: v1
kind: Service
metadata:
  name: voting-app-lb
  labels:
    app: voting-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/health"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: voting-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
spec:
  template:
    spec:
      containers:
      - name: voting-app
        env:
        - name: ENVIRONMENT
          value: "azure"
        - name: CLUSTER_TYPE
          value: "aks"